spring:
  datasource:
    url: jdbc:sqlite:../roco_encyclopedia.db

roco:
  media-path: ../media/
  frontend-path: ../frontend-data/

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
